sudo: false

language: php

php:
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm
  fast_finish: true

env:
  # trunk:
  - WP_VERSION=master WP_MULTISITE=0
  - WP_VERSION=master WP_MULTISITE=1
  # latest stable:
  - WP_VERSION=4.5.3 WP_MULTISITE=0
  - WP_VERSION=4.5.3 WP_MULTISITE=1
  # previous stable:
  - WP_VERSION=4.4.4 WP_MULTISITE=0
  - WP_VERSION=4.4.4 WP_MULTISITE=1
  # earliest supported:
  - WP_VERSION=3.9.2 WP_MULTISITE=0
  - WP_VERSION=3.9.2 WP_MULTISITE=1

notifications:
  email: false,
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cdf78658f24e0dac7ee0
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

git:
  depth: 1

install:
  # set up WP install
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - mkdir -p $WP_DEVELOP_DIR
  - cd $WP_DEVELOP_DIR
  - git clone --depth=1 git://develop.git.wordpress.org/ .
  # set up tests config
  - cp wp-tests-config-sample.php wp-tests-config.php
  - sed -i "s/youremptytestdbnamehere/wordpress_test/" wp-tests-config.php
  - sed -i "s/yourusernamehere/root/" wp-tests-config.php
  - sed -i "s/yourpasswordhere//" wp-tests-config.php
  # set up database
  - mysql -e 'CREATE DATABASE wordpress_test;' -uroot

script:
  - cd $TRAVIS_BUILD_DIR
  - |
    if [[ "$TRAVIS_PHP_VERSION" == "5.6" && "$WP_VERSION" == "master" && "$WP_MULTISITE" == "0" ]] ; then
        phpunit --coverage-clover=coverage.xml
    else
        phpunit
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
